---
title: "verify_estimators"
author: "Haotian Zheng"
date: "2024-08-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(SimEngine)
library(ggplot2)
```



This file try to verify the bias of Survival estimators, and the coverage of it using a Bootstrap method.
It can be ran both locally and in a cluster.
```{r}
create_data = function(n, surv_type, surv_params) {
  # id
  id = seq(1, n)
  
  # treatment
  treat = sample(0:1, n, replace = TRUE, prob = c(0.3, 0.7))
  
  # X1
  X1 = rnorm(n = n, mean = 24.3, sd = 8.38)
  
  # X2
  X2 = rnorm(n = n, mean = 266.84, sd = 507.82)
  
  # biomarker
  S = rtruncnorm(n = n, a = 0, b = 1, mean = 0.5, sd = 0.2) # truncated normal in (0, 1)
  prob_tmp = 1 / (1 + exp(- 0.05*X1 + 0.005*X2 + treat)) # to make edge_prob distributed not too extremely
  val_tmp = rbinom(n, prob = prob_tmp, size = 1)
  S = (1 - val_tmp) * S
  
  # survival time
  U = runif(n = n)
  if (surv_type == "Exponential") {
    lambda = surv_params
    t = -log(U) / (lambda * exp(0.15*X1 + 0.001*X2 - 5*S + treat))
  } else if (surv_type == "Gompertz") {
    alpha = surv_params[1]
    lambda = surv_params[2]
    t = 1/alpha * log(1 - (alpha * log(U)) / (lambda * exp(0.15*X1 + 0.001*X2 - 5*S + treat)))
  }
  
  # censore time
  U = runif(n = n)
  if (surv_type == "Exponential") {
    lambda = surv_params
    C = - log(U) / (lambda * exp(0.15*X1 + 0.001*X2))
  } else if (surv_type == "Gompertz") {
    alpha = surv_params[1]
    lambda = surv_params[2]
    C = (- 1/lambda * log(U) * exp(0.15*X1 + 0.001*X2)) ^ (alpha)
  }
  
  # delta
  delta = ifelse(t <= C, 1, 0)
  
  # observed time
  Y = pmin(t, C)
  
  # two-phase indicator
  t0 = 200 # set the time of interest
  prob_tmp = 1 / (1 + exp(0.15*X1 + 0.001*X2 - 1))
  Z = delta*I(Y <= t0) + (1 - delta*I(Y <= t0)) * rbinom(n = n, size = 1, prob = prob_tmp)
  
  # temporary dataframe
  data = data.frame("id" = id, "treat" = treat, "Y" = Y, "delta" = delta, "S" = S, "X1" = X1, "X2" = X2, "Z" = Z)
  
  # using ipwpoint function to generate inverse probability weights
  ip_weights = ipwpoint(
    exposure = Z,
    family = "binomial",  # The treatment is binary
    link = "logit",
    denominator = ~ treat + delta + S + X1 + X2,
    data = data
  )$ipw.weights
  #ip_weights = 1 / prob_tmp # we can also use this directly as the ip_weights
  
  # final data
  data = data %>% 
    dplyr::mutate(ipw = ip_weights)
  
  return(data)
}
```



functions of true survival, KM estimated, Coxph estimated and Two-phase sampling estimated
```{r}
# true survival function
surv_true = function(surv_type, surv_params, t, data) {
  if (surv_type == "Exponential") {
    lambda = surv_params
    Q_0 = exp(- lambda * t)
  } else if ( surv_type == "Gompertz") {
    alpha = surv_params[1]
    lambda = surv_params[2]
    Q_0 = exp(lambda/alpha * (1 - exp(alpha*t)))
  }
  unprop = 0.15*data$X1 + 0.001*data$X2 - 5*data$S + data$treat
  result = Q_0 ^ (exp(unprop))
  return(mean(result))
}

# Kaplan Meier estimated survival function
surv_km = function(t, data) {
  km.est = survfit(Surv(Y, delta) ~ 1, data = data, conf.type = "log-log")
  index = which.min(abs(km.est$time - t))
  result = km.est$surv[index]
  return(result)
}

# Coxph estimated survival function
surv_cox = function(model, t) {
  cox.est = survfit(model)
  index = which.min(abs(cox.est$time - t))
  result = cox.est$surv[index]
  return(result)
}

# Two Phase Sampling estimated survival function
surv_two = function(model, t, wt, data) {
  bh_1 = basehaz(model, centered = F)
  index = which.min(abs(bh_1$time - t))
  
  Q_0 = bh_1$hazard[index]
  
  beta = model$coefficients
  X_S = data[, c(names(model$coefficients))]
  unprop = exp(beta %*% t(X_S))
  
  result = exp(- Q_0 * wt * unprop)
  return(mean(result))
}
```



SE of KM estimator, Coxph estimator and Two-phase sampling estimator
```{r}
# SE for Kaplan Meier
se_km = function(t, data) {
  km.est = survfit(Surv(Y, delta) ~ 1, data = data, conf.type = "log-log")
  index = which.min(abs(km.est$time - t))
  result = summary(km.est)$std.err[index]
  return(result)
}

# SE for Coxph
se_cox = function(model, t) {
  cox.est = survfit(model)
  index = which.min(abs(cox.est$time - t))
  result = summary(cox.est)$std.err[index]
  return(result)
}

# SE for two-sphase sampling

```



Bootstrap function
```{r}
boot_ci = function(wt, data, t) {
  nn = nrow(data)
  R = 100
  surv_km.boot = c()
  surv_cox.boot = c()
  surv_two.boot = c()
  
  for (r in 1: R) {
    boot.samp = sample(1: nn, size = nn, replace = TRUE)
    data.boot = data[boot.samp, ]
    model.boot = coxph(Surv(Y, delta) ~ X1 + X2 + S, data = data.boot)
    surv_km.boot[r] = surv_km(t, data.boot)
    surv_cox.boot[r] = surv_cox(model.boot, t)
    surv_two.boot[r] = surv_two(model.boot, t, wt, data)
  }
  ci_km = quantile(surv_km.boot, prob = c(0.025, 0.975))
  ci_cox = quantile(surv_cox.boot, prob = c(0.025, 0.975))
  ci_two = quantile(surv_two.boot, prob = c(0.025, 0.975))
  km_se = sqrt(sum((surv_km.boot - mean(surv_km.boot)) ^ 2) / (R - 1))
  cox_se = sqrt(sum((surv_cox.boot - mean(surv_cox.boot)) ^ 2) / (R - 1))
  two_se = sqrt(sum((surv_two.boot - mean(surv_two.boot)) ^ 2) / (R - 1))
  result = data.frame(km_low = ci_km[1], km_up = ci_km[2], km_se = km_se,
                      cox_low = ci_cox[1], cox_up = ci_cox[2], cox_se = cox_se,
                      two_low = ci_two[1], two_up = ci_two[2], two_se = two_se)
  return(result)
}
```



```{r}
# start time
start_time = Sys.time()

# set up multi-cores
run_on_cluster(
  # use SimEngine
  first = {
    sim = new_sim()
    
    sim %<>% set_levels(
      # n = c(500, 1000, 2000, 4000),
      n = c(500, 1000),
      surv_time = list(
        "Exp" = list(surv_type = "Exponential", surv_params = 1.5e-2), # may be some problems
        "Gom" = list(surv_type = "Gompertz", surv_params = c(0.2138, 7e-8))
      )
    )
    
    sim %<>% set_config(num_sim = 100, n_cores = 4, seed = 1018,
                        packages = c("survival", "parallel", "truncnorm", "devtools", "ipw")
                        )
    
    sim %<>% set_script(function() {
      dat_phaseOne = create_data(L$n, L$surv_time$surv_type, L$surv_time$surv_params)
      model_one = coxph(Surv(Y, delta) ~ X1 + X2 + S + treat, data = dat_phaseOne)
      dat_phaseTwo = dat_phaseOne %>%
        dplyr::filter(Z == 1) # use phase two data
      model_two = coxph(Surv(Y, delta) ~ X1 + X2 + S + treat, data = dat_phaseTwo)
      wt_phase = nrow(dat_phaseTwo) / nrow(dat_phaseOne)
      
      # choose a specific time
      time_max = round(max(dat_phaseOne$Y))
      true = c()
      for (i in 1: time_max) {
        true[i] = surv_true(L$surv_time$surv_type, L$surv_time$surv_params, i, dat_phaseOne)
      }
      t = which.min(abs(true - 0.75))
      
      # bootstrap
      surv_ci = boot_ci(wt_phase, dat_phaseTwo, t)
      
      # get the Survival probability at the specific time point
      Q_true = surv_true(L$surv_time$surv_type, L$surv_time$surv_params, t, dat_phaseOne)
      Q_est_km = surv_km(t, dat_phaseTwo)
      Q_est_cox = surv_cox(model_two, t)
      Q_est_two = surv_two(model_two, t, wt_phase, dat_phaseTwo)
      
      # get the SE
      se_est_km = se_km(t, dat_phaseTwo)
      se_est_cox = se_cox(model_two, t)
      
      return(list(
        "Q_true" = Q_true,
        "Q_est_km" = Q_est_km,
        "Q_est_cox" = Q_est_cox,
        "Q_est_two" = Q_est_two,
        "km_low" = surv_ci$km_low,
        "km_up" = surv_ci$km_up,
        "se_km_boot" = surv_ci$km_se,
        "se_km_est" = se_est_km,
        "cox_low" = surv_ci$cox_low,
        "cox_up" = surv_ci$cox_up,
        "se_cox_boot" = surv_ci$cox_se,
        "se_cox_est" = se_est_cox,
        "two_low" = surv_ci$two_low,
        "two_up" = surv_ci$two_up,
        "se_two_boot" = surv_ci$two_se,
        "km_pctg" = (Q_est_km - Q_true) / Q_true * 100,
        "cox_pctg" = (Q_est_cox - Q_true) / Q_true * 100,
        "two_pctg" = (Q_est_two - Q_true) / Q_true *100,
        "se_km_pctg" = (surv_ci$km_se - se_est_km) / se_est_km * 100,
        "se_cox_pctg" = (surv_ci$cox_se - se_est_cox) / se_est_cox * 100,
        ".complex" = list(
          "model" = model_two,
          "data" = dat_phaseTwo,
          "ci" = surv_ci
        )
      ))
    })
  },
  
  main = {
    sim %<>% run()
    print(sim$errors)
  },
  
  last = {
    # mean
    Q_true = sim %>% SimEngine::summarize(list(stat = "mean", x = "Q_true"))
    Q_est_km = sim %>% SimEngine::summarize(list(stat = "mean", x = "Q_est_km"))
    Q_est_cox = sim %>% SimEngine::summarize(list(stat = "mean", x = "Q_est_cox"))
    Q_est_two = sim %>% SimEngine::summarize(list(stat = "mean", x = "Q_est_two"))
    # bias
    bias_Q = sim %>% SimEngine::summarize(
      list(stat = "bias", estimate = "Q_est_km", truth = "Q_true", name = "bias_km"),
      list(stat = "bias", estimate = "Q_est_cox", truth = "Q_true", name = "bias_cox"),
      list(stat = "bias", estimate = "Q_est_two", truth = "Q_true", name = "bias_twophase"),
      list(stat = "coverage", lower = "km_low", upper = "km_up", truth = "Q_true", name = "cov_surv_km"),
      list(stat = "coverage", lower = "cox_low", upper = "cox_up", truth = "Q_true", name = "cov_surv_cox"),
      list(stat = "coverage", lower = "two_low", upper = "two_up", truth = "Q_true", name = "cov_surv_twophase")
    )
    # bias percentage
    bias_Q_pct = sim %>% SimEngine::summarize(
      list(stat = "mean", x = "km_pctg", name = "bias_km_pct"),
      list(stat = "mean", x = "cox_pctg", name = "bias_cox_pct"),
      list(stat = "mean", x = "two_pctg", name = "bias_twophase_pct")
    )
    # SE accuracy
    accuracy_se = sim %>% SimEngine::summarize(
      list(stat = "mean", x = "se_km_boot", name = "bias_se_km"),
      list(stat = "mean", x = "se_cox_boot", name = "bias_se_cox"),
      list(stat = "mean", x = "se_two_boot", name = "bias_se_two"),
      list(stat = "mean", x = "se_km_pctg", name = "se_bias_km_pct"),
      list(stat = "mean", x = "se_cox_pctg", name = "se_bias_cox_pct")
    )
  },
  
  cluster_config = list(js = "slurm")
)



# end time
end_time = Sys.time()
execution_time = end_time - start_time
print(execution_time)
```



plot
```{r}
ggplot(data.frame(
  n = rep(c(500, 1000, 2000, 4000), 6),
  surv = c(Q_true$mean_Q_true[1: 4], Q_est_cox$mean_Q_est_cox[1: 4], Q_est_two$mean_Q_est_two[1: 4],
           Q_true$mean_Q_true[5: 8], Q_est_cox$mean_Q_est_cox[5: 8], Q_est_two$mean_Q_est_two[5: 8]),
  which = rep(c("True Survival", "Coxph_estimator", "Twophase_estimator"), each = 4, times = 2),
  model = rep(c("Exponential", "Gompertz"), each = 12)
), aes(x = n, y = surv, color = factor(which))) +
  geom_line() +
  labs(color = "Method", y = "survival function", x = "Sample size (per group)") +
  facet_wrap(~ model) +
  theme_minimal()
```



